name: ApiDoc
on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches: [refactoring]
    paths:
      - .github/workflows/api_doc.yml
      - api/**
  push:
    branches: [refactoring]
    paths:
      - .github/workflows/api_doc.yml
      - api/**

jobs:
  CheckApiDoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: jetbrains
          java-version: 21

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Disable Gradle toolchain auto-download in CI
        run: mkdir -p ~/.gradle && echo 'org.gradle.java.installations.auto-download=false' >> ~/.gradle/gradle.properties

      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Check doc
        run: ./gradlew api:dokkaGenerateHtml